api:
  # Do not use trailing spaces for the baseUrl
  baseUrl: API_BASE_URL
  host: API_HOST
  port: API_PORT
  version: API_VERSION

admin:
  url: ADMIN_URL
  recoverPath: ADMIN_RECOVER_PATH

auth:
  successRedirect: AUTH_SUCCESS_REDIRECT
  providers:
    googleLogin:
      enabled: AUTH_PROVIDER_GOOGLE_ENABLED
      clientID: AUTH_PROVIDER_GOOGLE_CLIENT_ID
      clientSecret: AUTH_PROVIDER_GOOGLE_CLIENT_SECRET
    twitterLogin:
      enabled: AUTH_PROVIDER_TWITTER_ENABLED
      consumerKey: AUTH_PROVIDER_TWITTER_CONSUMER_KEY
      consumerSecret: AUTH_PROVIDER_TWITTER_CONSUMER_SECRET

mongodb:
  url: MONGODB_URL

settings:
  registrationEnabled: SETTINGS_REGISTRATION_ENABLED

smtp:
  host: SMTP_HOST
  port: SMTP_PORT

storage:
  path: STORAGE_PATH

system:
  initdb: INITDB
  migratedb: MIGRATEDB
