api:
  # Do not use trailing spaces for the baseUrl
  baseUrl: http://127.0.0.1:3000
  version: api/v1

admin:
  url: http://127.0.0.1:9000
  recoverPath: /#/password-reset

mongodb:
  url: false

settings:
  registrationEnabled: true
  multiDomain: true

smtp:
  host: false
  port: false

storage:
  path: './storage'

system:
  initdb: false
  migratedb: false
