notifications:
  email: false
  slack: colmena-cms:o0Inc1h1waa9OKMvL4GiTbDW
language: node_js
node_js:
- '8'
script:
- npm run build
cache:
  yarn: true
  directories:
  - apps/admin/node_modules
  - apps/api/node_modules
  - node_modules

deploy:
  - provider: script
    skip_cleanup: true
    script: ./bin/deploy-to-now.sh
    on:
      branch: develop

