api:
  baseUrl: API_BASE_URL
  version: API_VERSION

db:
  url: MONGODB_URL

storage:
  path: STORAGE_PATH

settings:
  registrationEnabled: SETTINGS_REGISTRATION_ENABLED
  multiDomain: SETTINGS_MULTI_DOMAIN

system:
  initdb: INITDB
